### ISSUE TITLE
Python 3 Support: NameError: name 'unicode' is not defined

### ISSUE THREAD

**Issue by arky** [okfn/ckanext-vegaview#6]
Perhaps this ckan extension needs to be updated for Python 3 

```python 

ckan-dev_1    | Traceback (most recent call last):
ckan-dev_1    |   File "/usr/lib/python3.8/site-packages/flask/app.py", line 2449, in wsgi_app
ckan-dev_1    |     response = self.handle_exception(e)
ckan-dev_1    |   File "/usr/lib/python3.8/site-packages/flask/app.py", line 1866, in handle_exception
ckan-dev_1    |     reraise(exc_type, exc_value, tb)
ckan-dev_1    |   File "/usr/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
ckan-dev_1    |     raise value
ckan-dev_1    |   File "/usr/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
ckan-dev_1    |     response = self.full_dispatch_request()
ckan-dev_1    |   File "/usr/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
ckan-dev_1    |     rv = self.handle_user_exception(e)
ckan-dev_1    |   File "/usr/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
ckan-dev_1    |     reraise(exc_type, exc_value, tb)
ckan-dev_1    |   File "/usr/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
ckan-dev_1    |     raise value
ckan-dev_1    |   File "/usr/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
ckan-dev_1    |     rv = self.dispatch_request()
ckan-dev_1    |   File "/usr/lib/python3.8/site-packages/flask_debugtoolbar/__init__.py", line 125, in dispatch_request
ckan-dev_1    |     return view_func(**req.view_args)
ckan-dev_1    |   File "/srv/app/src/ckan/ckan/views/resource.py", line 561, in views
ckan-dev_1    |     return base.render(
ckan-dev_1    |   File "/srv/app/src/ckan/ckan/lib/base.py", line 151, in render
ckan-dev_1    |     return flask_render_template(template_name, **extra_vars)
ckan-dev_1    |   File "/usr/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
ckan-dev_1    |     return _render(
ckan-dev_1    |   File "/usr/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
ckan-dev_1    |     rv = template.render(context)
ckan-dev_1    |   File "/usr/lib/python3.8/site-packages/jinja2/asyncsupport.py", line 76, in render
ckan-dev_1    |     return original_render(self, *args, **kwargs)
ckan-dev_1    |   File "/usr/lib/python3.8/site-packages/jinja2/environment.py", line 1008, in render
ckan-dev_1    |     return self.environment.handle_exception(exc_info, True)
ckan-dev_1    |   File "/usr/lib/python3.8/site-packages/jinja2/environment.py", line 780, in handle_exception
ckan-dev_1    |     reraise(exc_type, exc_value, tb)
ckan-dev_1    |   File "/usr/lib/python3.8/site-packages/jinja2/_compat.py", line 37, in reraise
ckan-dev_1    |     raise value.with_traceback(tb)
ckan-dev_1    |   File "/srv/app/src/ckan/ckan/templates/package/resource_views.html", line 2, in <module>
ckan-dev_1    |     {% extends "package/resource_edit_base.html" %}
ckan-dev_1    |   File "/srv/app/src/ckan/ckanext/datastore/templates/package/resource_edit_base.html", line 1, in <module>
ckan-dev_1    |     {% ckan_extends %}
ckan-dev_1    |   File "/srv/app/src/ckan/ckanext/datapusher/templates/package/resource_edit_base.html", line 1, in <module>
ckan-dev_1    |     {% ckan_extends %}
ckan-dev_1    |   File "/srv/app/src/ckan/ckan/templates/package/resource_edit_base.html", line 4, in <module>
ckan-dev_1    |     {% set res = resource %}
ckan-dev_1    |   File "/srv/app/src/ckan/ckan/templates/package/base.html", line 4, in <module>
ckan-dev_1    |     {% set dataset_type = dataset_type or pkg.type or 'dataset' %}
ckan-dev_1    |   File "/srv/app/src/ckan/ckan/templates/page.html", line 1, in <module>
ckan-dev_1    |     {% extends "base.html" %}
ckan-dev_1    |   File "/srv/app/src/ckan/ckan/templates/base.html", line 106, in <module>
ckan-dev_1    |     {%- block page %}{% endblock -%}
ckan-dev_1    |   File "/srv/app/src/ckan/ckan/templates/page.html", line 19, in <module>
ckan-dev_1    |     {%- block content %}
ckan-dev_1    |   File "/srv/app/src/ckan/ckan/templates/page.html", line 22, in <module>
ckan-dev_1    |     {% block main_content %}
ckan-dev_1    |   File "/srv/app/src/ckan/ckan/templates/page.html", line 74, in <module>
ckan-dev_1    |     {% block primary %}
ckan-dev_1    |   File "/srv/app/src/ckan/ckan/templates/page.html", line 87, in <module>
ckan-dev_1    |     {% block primary_content %}
ckan-dev_1    |   File "/srv/app/src/ckan/ckan/templates/page.html", line 102, in <module>
ckan-dev_1    |     {% if self.page_primary_action() | trim %}
ckan-dev_1    |   File "/srv/app/src/ckan/ckan/templates/package/resource_views.html", line 14, in <module>
ckan-dev_1    |     {% for option in h.get_allowed_view_types(resource, pkg_dict)  %}
ckan-dev_1    |   File "/srv/app/src/ckan/ckan/lib/helpers.py", line 2458, in get_allowed_view_types
ckan-dev_1    |     plugins = datapreview.get_allowed_view_plugins(data_dict)
ckan-dev_1    |   File "/srv/app/src/ckan/ckan/lib/datapreview.py", line 149, in get_allowed_view_plugins
ckan-dev_1    |     plugin_info = plugin.info()
ckan-dev_1    |   File "/srv/app/src/ckanext-vegaview/ckanext/vegaview/plugin.py", line 24, in info
ckan-dev_1    |     'vega_specification': [not_empty, unicode],
ckan-dev_1    | NameError: name 'unicode' is not defined

```

**Comment by momarious** [comment]
Hello sir did you finnally find the result ?? I have the same issue
